[package]
name = "day16"
version = "0.1.1"
edition = "2021"

[dependencies]
criterion = "0.5.1"
# fancy-regex = "0.14.0"
# md-5 = "0.10.6"
# priority-queue = "2.1.2"
# regex = "1.11.1"

[[bench]]
name = "bench"
harness = false